version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACE_WITH_TASK_DEFINITION"
        LoadBalancerInfo:
          ContainerName: "tollapp-bluegreen"
          ContainerPort: 8080