version: 0.2

phases:
  install:
    commands:
      - echo "Install phase — no dependencies."

  build:
    commands:
      - echo "Build phase — skipping for static content."

  post_build:
    commands:
      - echo "Post-build — preparing deployment package."
      - echo "Creating appspec.yaml..."
      - |
        cat <<EOF > appspec.yaml
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "REPLACED_AT_DEPLOY"
                LoadBalancerInfo:
                  ContainerName: "nginx"
                  ContainerPort: 80
        EOF

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json