version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building project...
      - # Add your build commands here if any, like npm build
  post_build:
    commands:
      - echo Build completed.
      - # You can add commands to test or package your application here

artifacts:
  files:
    - '**/*'
  discard-paths: no